---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name}}-deployment 
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.name}}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.name}}  
  template:
    metadata:
      labels:
        app: ${{values.name}}  
    spec:
      containers:
      - name: ${{values.name}} 
        image: container-image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: ${{values.request_memory | dump}} 
            cpu: ${{values.request_cpu | dump}} 
          limits:
            memory: ${{values.limit_memory | dump}} 
            cpu: ${{values.limit_cpu | dump}} 