---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ${{values.name}}
  name: ${{values.name}}
  namespace: ${{values.namespace}}
automountServiceAccountToken: false