---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{values.namespace}}

bases:
  - ../../base/${{values.name}}

images:
  - name: container-image
    newName: ${{values.image_tag}}
